### ISSUE TITLE
Supporting HTML and Excel(CSV) format

### ISSUE THREAD

**Issue by kazuhiro4949** [yahoojapan/XCMetricsAggregator#1]
### TODO

 - [ ] CSV, table format https://github.com/yahoojapan/XCMetricsAggregator/pull/11
 - [ ] CSV, chart format
 - [ ] HTML, table format
 - [ ] HTML, chart format
